---
- name: Devops Project \#2 Monitoring Playbook
  hosts: webservers
  remote_user: root
  roles:
    - { role: datadog.datadog, become: yes }
  vars:
    datadog_api_key: "{{ datadog_api_key }}"
    datadog_site: "datadoghq.eu"
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: Application health check status
            url: http://localhost:80
            timeout: 5
            method: GET

  tasks:
    - name: Install and run Datadog agent.
      include_role:
        name: datadog.datadog
