---
- hosts: all
  vars:
    pip_install_packages:
      - name: docker

  # https://stackoverflow.com/questions/41535838/how-to-run-apt-update-and-upgrade-via-ansible-shell
  pre_tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

  roles:
    - geerlingguy.pip
    # - datadog.datadog
  
  tasks:
    - name: Create .env For Containers
      template:
        src: env.j2
        dest: '.env'

    - name: Run Redmine Container
      docker_container:
        name: redmine
        image: redmine
        state: started
        restart: yes
        published_ports:
          - 80:{{ redmine_app_port }}
        env_file: .env
