---
driver:
  name: vagrant

provisioner:
  # use an ansible playbook to provision our server
  name: ansible_playbook
  # name of the host
  hosts: test-kitchen
  # list of ansible galaxy requirements from the roles meta/main.yml
  # requirements_path: dependencies.yml

platforms:
  - name: ubuntu-18.10

suites:
  # suites found at /test/integration/$test-name
  - name: default