---
- name: Create .env For Containers
  template:
    src: env.j2
    dest: '.env'

- name: Run Redmine Container
  docker_container:
    name: redmine
    image: redmine:{{ redmine_version }}
    state: started
    restart: yes
    published_ports:
      - 80:{{ redmine_app_port }}
    env_file: .env
